site_name: Tusmo
docs_dir: docs-src
site_description: Luqad barnaamijka Soomaaliga ah oo loo turjumo C
site_url: https://tusmolang.github.io/Tusmo/

nav:
  - Hoyga: index.md
  - Bilaabista: getting-started.md
  - Sida ay u shaqeyso: how-it-works.md
  - Luqadda:
      - Doorsoomayaasha: variables.md
      - Erayada: strings.md
      - Tixyada: arrays.md
      - Qaamuusyada: dictionaries.md
      - Hawl-wadeennada: operators.md
      - Xaaladaha: conditions.md
      - Wareegyada: loops.md
      - Hawlaha: functions.md
      - Kooxaha: classes.md
  - Maktabadda Caadiga ah:
      - Dulmar: stdlib.md
      - OS: stdlib-os.md
      - Wakhti: stdlib-wakhti.md
      - Nasiib: stdlib-nasiib.md
      - Xiriiriye: stdlib-xiriiriye.md
      - WebXiriiriye: stdlib-webxiriiriye.md
      - HTTP: stdlib-http.md

repo_url: https://github.com/TusmoLang-org/Tusmo

repo_url: https://github.com/TusmoLang-org/Tusmo
repo_name: TusmoLang-org/Tusmo

theme:
  name: material
  palette:
    - scheme: slate
      primary: deepPurple
      accent: cyan
      toggle:
        icon: material/weather-night
        name: Switch to light mode
  favicon: favicon.svg
  logo: favicon.svg

markdown_extensions:
  - admonition
  - codehilite
  - toc:
      permalink: true
