site_name: Tusmo
docs_dir: docs-src
site_description: Luqad barnaamijka Soomaaliga ah oo loo turjumo C
site_url: https://tusmolang.github.io/Tusmo/

repo_url: https://github.com/Tusmolang/Tusmo
repo_name: Tusmolang/Tusmo

theme:
  name: material
  palette:
    - scheme: slate
      primary: deepPurple
      accent: cyan
      toggle:
        icon: material/weather-night
        name: Switch to light mode
  favicon: favicon.svg
  logo: favicon.svg

markdown_extensions:
  - admonition
  - codehilite
  - toc:
      permalink: true
